name: CrazyAuctions
author: BadBones69
main: me.badbones69.crazyauctions.Main
website: https://www.spigotmc.org/resources/authors/kicjow.9719/
version: 1.2.6.MPDB
depend: [Vault]
description: >
             A plugin to auction off items globally.
commands:
  ca:
    description: Opens the Crazy Auctions GUI.
    aliases: [crazyauction, crazyauctions, ah, hdv]